name: Tests

on: 
  pull_request:
  push:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.2-xenial
          - swift:5.2-bionic
          - swiftlang/swift:nightly-master-focal
        include:
          - image: swiftlang/swift:nightly-master-centos8
            depscmd: dnf install -y zlib-devel
          - image: swiftlang/swift:nightly-master-amazonlinux2
            depscmd: yum install -y zlib-devel
    container: ${{ matrix.image }}
    steps:
    - name: Install dependencies if needed
      run: ${{ matrix.depscmd }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: swift test --enable-test-discovery
  osx:
    runs-on: macOS-latest
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@1.0
        with: { 'xcode-version': 'latest' }
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: swift test --enable-test-discovery
